---
pipeline:
  docker:
    image: plugins/docker
    repo: docker-registry.labs.devops.dance/${DRONE_REPO_NAME}
    tags:
      - ${DRONE_COMMIT:0:7}

  deploy:
    image: python:2
    environment:
      - NOMAD_URL=https://nomad.labs.devops.dance/v1/jobs
      - DOCKER_REPOSITORY_HOST=docker-registry.labs.devops.dance
    commands:
      - pip install PyYaml jinja2 requests raven
      - curl -SsLO https://raw.githubusercontent.com/bjarocki/ok-tools/master/nomad-job-builder.py
      - python nomad-job-builder.py
    when:
      branch: master
